name: Deploy to GitHub Pages
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Event ${{ github.event_name }} os ${{ runner.os }} repo ${{ github.repository }} branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Build
        run: yarn nx run ng-yacg:build --prod
      - name: List files in the repository
        run: |
          rm -rf node_modules
          ls -R ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
