name: Deploy to GitHub Pages
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Event ${{ github.event_name }} os ${{ runner.os }} repo ${{ github.repository }} branch ${{ github.ref }}."
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: yarn install
      - run: DEBUG=* yarn nx run ng-yacg:build:production --progress --verbose --output-path dist/ --output-hashing none
      - name: List files in the repository
        run: |
          rm -rf node_modules
          ls -R ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
